<?xml version="1.0" encoding="UTF-8"?>
<definitions
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  targetNamespace="http://siebel.com/asi/"
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:tns="http://siebel.com/asi/"
>
  <types
  ></types
  >
  <message
    name="CreatePayment_Input"
  >
    <part
      name="InvoiceNum"
      type="xsd:string"
    ></part
    >
    <part
      name="PaymentType"
      type="xsd:string"
    ></part
    >
    <part
      name="InvioceCorp"
      type="xsd:string"
    ></part
    >
    <part
      name="Comments"
      type="xsd:string"
    ></part
    >
    <part
      name="AdvanceId"
      type="xsd:string"
    ></part
    >
    <part
      name="PaymentId"
      type="xsd:string"
    ></part
    >
    <part
      name="AccountNum"
      type="xsd:string"
    ></part
    >
    <part
      name="ReceiptDate"
      type="xsd:string"
    ></part
    >
    <part
      name="ReceiptId"
      type="xsd:string"
    ></part
    >
    <part
      name="OrderNum"
      type="xsd:string"
    ></part
    >
    <part
      name="AdvanceAmount"
      type="xsd:string"
    ></part
    >
    <part
      name="PaymentCorp"
      type="xsd:string"
    ></part
    >
    <part
      name="Amount"
      type="xsd:string"
    ></part
    >
    <part
      name="Type"
      type="xsd:string"
    ></part
    >
    <part
      name="Currency"
      type="xsd:string"
    ></part
    >
    <part
      name="ReceiptNum"
      type="xsd:string"
    ></part
    >
    <part
      name="AdvanceFlg"
      type="xsd:string"
    ></part
    >
    <part
      name="Source"
      type="xsd:string"
    ></part
    >
    <part
      name="AdvanceBalance"
      type="xsd:string"
    ></part
    >
  </message
  >
  <message
    name="CreatePayment_Output"
  >
    <part
      name="ErrorCode"
      type="xsd:string"
    ></part
    >
    <part
      name="ErrorMessage"
      type="xsd:string"
    ></part
    >
  </message
  >
  <portType
    name="GLD_spcPayment_spcInbound_spcFor_spcERP_spcBS"
  >
    <operation
      name="CreatePayment"
    >
      <input
        message="tns:CreatePayment_Input"
      ></input
      >
      <output
        message="tns:CreatePayment_Output"
      ></output
      >
    </operation
    >
  </portType
  >
  <binding
    name="GLD_spcPayment_spcInbound_spcFor_spcERP_spcBS"
    type="tns:GLD_spcPayment_spcInbound_spcFor_spcERP_spcBS"
  >
    <soap:binding
      transport="http://schemas.xmlsoap.org/soap/http"
      style="rpc"
    ></soap:binding
    >
    <operation
      name="CreatePayment"
    >
      <soap:operation
        soapAction="rpc/http://siebel.com/asi/:CreatePayment"
      ></soap:operation
      >
      <input
      >
        <soap:body
          namespace="http://siebel.com/asi/"
          use="literal"
        ></soap:body
        >
      </input
      >
      <output
      >
        <soap:body
          namespace="http://siebel.com/asi/"
          use="literal"
        ></soap:body
        >
      </output
      >
    </operation
    >
  </binding
  >
  <service
    name="GLDPaymentInboundForERP"
  >
    <port
      binding="tns:GLD_spcPayment_spcInbound_spcFor_spcERP_spcBS"
      name="GLD_spcPayment_spcInbound_spcFor_spcERP_spcBS"
    >
      <soap:address
        location="http://192.168.28.23:8080/eai_chs/start.swe?SWEExtSource=WebService&amp;SWEExtCmd=Execute&amp;UserName=gldadmin&amp;Password=123qweADMIN"
      ></soap:address
      >
    </port
    >
  </service
  >
</definitions
>